{
 "title": "NBomber",
 "time": { "from": "2021-05-14T16:06:44.561Z", "to": "2021-05-14T16:07:23.027Z" },
 "templating": {
  "list": [
   {
    "name": "test_suite",
    "query": "SHOW TAG VALUES WITH KEY = \"test_suite\""
   },
   {
    "name": "test_name",
    "query": "SHOW TAG VALUES WITH KEY = \"test_name\"  WHERE test_suite=~ /^$test_suite$/"
   },
   {
    "name": "session_id",
    "query": "SHOW TAG VALUES WITH KEY = \"session_id\"   WHERE test_suite=~ /^$test_suite$/ AND  test_name=~ /^$test_name$/"
   },
   {
    "name": "scenario",
    "query": "SHOW TAG VALUES WITH KEY = \"scenario\"  WHERE session_id=~ /^$session_id$/"
   },
   {
    "name": "step",
    "query": "SHOW TAG VALUES WITH KEY = \"step\" WHERE session_id=~ /^$session_id$/  AND scenario=~ /^$scenario$/"
   }
  ]
 },
 "panels": [
  { "title": "scenario stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ok requests count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_step]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nbomber__ok.request.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    }
   ]
  },
  {
   "title": "failed requests count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_step]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nbomber__fail.request.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    }
   ]
  },
  {
   "title": "requests",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ok",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nbomber__ok.request.count",
     "query": "SELECT last(\"value\") FROM \"nbomber__ok.request.count\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"scenario\" =~ /^$scenario$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nbomber__fail.request.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    }
   ]
  },
  { "title": "step stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "ok stats",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "requests count",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "nbomber__ok.request.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "RPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "nbomber__ok.request.rps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "latency min",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "nbomber__ok.latency.minms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    }
   ]
  },
  {
   "title": "load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "load simulation" }
   ],
   "targets": [
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__simulation.value",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    }
   ]
  },
  {
   "title": "throuhput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "reqps", "label": "RPS" }
   ],
   "targets": [
    {
     "alias": "RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__ok.request.rps",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    }
   ]
  },
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "latency, requests" }
   ],
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__ok.latency.minms",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__fail.latency.meanms",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__fail.latency.maxms",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    },
    {
     "alias": "50%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__ok.latency.percent50",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    },
    {
     "alias": "75%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__ok.latency.percent75",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    },
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__ok.latency.percent99",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    }
   ]
  },
  {
   "title": "data transfer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes", "label": "data" }
   ],
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__fail.datatransfer.minbytes",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__ok.datatransfer.meanbytes",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__fail.datatransfer.maxbytes",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    },
    {
     "alias": "50%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__ok.datatransfer.percent50",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    },
    {
     "alias": "75%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__ok.datatransfer.percent75",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    },
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_id" ], "type": "tag" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "nbomber__fail.datatransfer.percent99",
     "query": "SELECT mean(\"value\") FROM \"nbomber__fail.request.rps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "session_id", "operator": "=~", "value": "/^$session_id$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" }
     ]
    }
   ]
  }
 ]
}